### ISSUE TITLE
The download button on the page doesn't work

### ISSUE THREAD

**Issue by Tresquel** [constantinDev/cumclient#1]
Self explanatory

**Comment by constantinDev** [comment]
i know that, there isnt actually a release or an installer for the client yet. thats why the button doesnt work. Pre-releases can be found in the tags section on the github tho

**Comment by Tresquel** [comment]
That's ok i like the project and imma help you out when I learn a thing or too

**Comment by constantinDev** [comment]
Thanks. If i get the installer or an actual release ready, the button will work
